app:
  name: yummies
otel:
  endpoint: http://yummies.local:4317
fluentd:
  host: yummies.local
  port: 24224
  network: tcp
  json: true
  tag: my.logs 
grpc:
  port: 50051
nats:
  url: 'nats://yummies.local:4222'
mongodb:
  uri: 'mongodb://yummies:yummies@yummies.local:27017/yummies?authMechanism=PLAIN'
http:
  addr: '0.0.0.0:9090'
