import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="${inter.className} mocha dark:bg-ctp-mantle border dark:border-ctp-mantle w-screen h-screen" suppressHydrationWarning={true}>{children}</body>
        </html>
    );
}
