# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
      - targets:
        # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
          - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
          - targets: ["node-exporter:9100"]

  - job_name: "metrics-events"
    static_configs:
          - targets: ["metrics-kafka:8080"]

  - job_name: "catalog-http"
    static_configs:
          - targets: ["catalog-http:8080"]

  - job_name: "purchasing-http"
    static_configs:
          - targets: ["purchasing-http:8080"]

  - job_name: "purchasing-kafka"
    static_configs:
          - targets: ["purchasing-kafka:8080"]

  - job_name: "sales-http"
    static_configs:
          - targets: ["sales-http:8080"]

  - job_name: "sales-grpc"
    static_configs:
          - targets: ["sales-grpc:8080"]

  - job_name: "sales-kafka"
    static_configs:
          - targets: ["sales-kafka:8080"]

  - job_name: "warehouse-http"
    static_configs:
          - targets: ["warehouse-http:8080"]

  - job_name: "warehouse-kafka"
    static_configs:
          - targets: ["warehouse-kafka:8080"]

  - job_name: "ws-gateway"
    static_configs:
          - targets: ["ws-gateway:8080"]

  - job_name: "dash"
    static_configs:
          - targets: ["dash:9100"]
