app:
  name: delivery
otel:
  endpoint: http://delivery.local:4317
fluentd:
  host: delivery.local
  port: 24224
  network: tcp
  json: true
  tag: my.logs 
grpc:
  port: 50051
nats:
  url: "nats://delivery.local:4222"
mongodb:
  uri: "mongodb://delivery:delivery@delivery.local:27017/delivery?authMechanism=PLAIN"
